# Generated by Django 3.1.4 on 2020-12-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201228_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем расширяемой память'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD-карты'),
        ),
    ]
